* Opera UserJS Collection

  This is a collection of UserJS scripts for [[http://opera.com/][Opera web browser]] that
  I have written or at least modified in big part and I am using.

** follow.js

   [[file:follow.js][Link Follow Scrpit]] is a script for following links and form
   fields.  Upon pressing “f” a label appears on top of every link and
   form field.  By typing the label you choose (ie. click or bring
   focus to) the element.

   The script is based on the script form the [[http://www.uzbl.org][uzbl web browser]]'s
   script with the same function.

*** Installation & configuration

    Refer to the “Installation & configure” section of this document
    at the end.  Besides what's written there, [[file:follow.js][Link Follow Scrpit]] has
    some other configuration options as well:

    Most importantly, you need to configure the set of characters you
    want the script to use -- it is specified by a “charset” variable
    near the beginning of the script.  By default it is set to use
    only right side of a keyboard in qwerty layout.  You may easily
    change the characters by uncommenting one of the example lines or
    setting it by yourself.

    There is also a “retMode” which turns the “retMode” by default.
    If you like it to be on by default set this variable to ”true”.

** tip.js

   [[file:tip.js][ToolIip]] is a script which shows information about hovered object in
   lower left corner.  This is a replacement for tooltips and status
   bar which has no delay (opposite to tooltips) and requires no space
   on browser's user interface (so you can completely turn status bar
   and address bar off).

   It is also more functional in the sense that it is not limited to
   showing only address of a link and title of an element.  It also
   shows an alternative text and source of images.

** backspace-blur.js

   [[file:backspace-blur.js][Blur on backspace]] is a script which removes focus from form fields
   when backspace is pressed and the field is empty.  This may sound
   useless but it has proven quite handy for me.

** Installation & configuration

   To install the script simply copy the .js file to your UserJS
   directory.  You may find UJSManager handy in installation.  For
   more information about UserJS in Opera refer to documentation and
   Google.

   After this is done, the script should start working smoothly.
   Usually, some configuration is possible via changing the script.
   If that's the case, there will be several variables at the
   beginning of the script that you can safely modify.  Refer to
   script's source code as well as documentation in this document for
   more information.

   Script that use custom styles have “style” variable with the styles
   included.  You can modify it as you want to change the appearance
   of elements used by the script.

   Alternatively, you can just comment the whole line out and copy the
   style to your UserCSS file.  Be sure to change “\\” inside to
   a singe “\” (for instance in “content: "\\00A0"” in [[file:follow.js][Link Follow
   Scrpit]]).  The style has “!important” tags included so you should
   not need to worry about
